import type { Metadata } from "next";
import { Geist, Geist_Mono, Inconsolata } from "next/font/google";
import "./globals.css";

// Cargar la fuente correctamente con `subsets`
const inconsolata = Inconsolata({
  subsets: ["latin"],
  variable: "--font-inconsolata-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inconsolata.variable}>
      <body className="antialiased">{children}</body>
    </html>
  );
}
